[package]
name = "abstracted_mesh_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.2"
serde = "1.0.185"
serde_json = "1.0.105"
bevy_panorbit_camera = "0.8"